name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          version: ${{ matrix.node-version }}
