name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-and-build
      with:
        node-version: ${{ matrix.node-version }}
