# This workflow will create a GitHub release with a zip attachment

name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build
      - name: Create zip file for release
        run: |
          mv dist cocoda
          zip -r "cocoda-$(git describe --tags).zip" cocoda
      - name: Set artifact name
        run: |
          echo "ARTIFACT_NAME=$(ls cocoda-*.zip)" >> $GITHUB_ENV
      - run: |
          echo "ARTIFACT_NAME=$(ls cocoda-*.zip)" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Cocoda ${{ github.ref_name }}
          body: TODO
          draft: true
          prerelease: false
          files: ${{ env.ARTIFACT_NAME }}
